export type InputProps = {
	id?: string;
	type?: string;
	width?: string;
	height?: string;
	margin?: string;
	padding?: string;
	alignself?: string;
	backgroundColor?: string;
	border?: string;
	borderFocused?: string;
	borderHover?: string;
	borderRadius?: string;
	boxShadow?: string;
	text?: string;
	textColor?: string;
	textTransform?: string;
	fontSize?: string;
	onClick?: React.MouseEventHandler<HTMLDivElement>;
	autoFocus?: boolean;
	iconStart?: React.ReactNode;
	iconEnd?: React.ReactNode;
	tabIndex?: number;
	textSpan?: string;
	errorMessage?: string;
	disabled?: boolean;
	placeholder?: string;
	value: string;
	setValue: (value: string) => void;
};

export type InputStyleProps = {
	id?: string;
	type?: string;
	width?: string;
	height?: string;
	margin?: string;
	padding?: string;
	alignself?: string;
	backgroundColor?: string;
	border?: string;
	borderFocused?: string;
	borderHover?: string;
	borderRadius?: string;
	boxShadow?: string;
	text?: string;
	textColor?: string;
	textTransform?: string;
	fontSize?: string;
	autoFocus?: boolean;
	iconStart?: React.ReactNode;
	iconEnd?: React.ReactNode;
	tabIndex?: number;
	textSpan?: string;
	errorMessage?: string;
	disabled?: boolean;
	placeholder?: string;
};
